### Read all products
GET http://localhost:3000/products-api/products

### Read products by brand
GET http://localhost:3000/products-api/products/Lenovo

### CREATE new product({productid,name,brand,price})
POST http://localhost:3000/products-api/products
Content-Type: application/json

{
    "productId":1,
    "name":"Laptop",
    "brand":"Lenovo",
    "price":70000
}

###
PUT http://localhost:3000/products-api/products
Content-Type: application/json

{
    "productId":1,
    "name":"Laptop",
    "brand":"Dell",
    "price":70000
}

###
DELETE http://localhost:3000/products-api/products/1