### Admin login
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "email":"admin1@mail.com",
    "password":"admin1"
}

### Admin logout
GET http://localhost:4000/auth/logout

### read all articles of all authors
GET http://localhost:4000/admin-api/articles

###Block or activate User or Author
PUT http://localhost:4000/admin/state
Content-Type: application/json

{
    "mail":"",
    "toBeActive":""
}