### Register Author
POST http://localhost:4000/auth/users
Content-Type: application/json

{
  "firstName": "author3",
  "lastName": "",
  "email": "author3@mail.com",
  "role": "AUTHOR",
  "password": "author3",
  "profileImageURL": ""
}

### author login
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "email":"author2@mail.com",
    "password":"author2"
}

### author Logout
GET http://localhost:4000/auth/logout

### Create new Article
POST http://localhost:4000/author-api/articles
Content-Type: application/json

{
  "title": "Article1 by author2",
  "content": "Very Good article"
}

### read own articles
GET http://localhost:4000/author-api/articles

### update article by author
PUT http://localhost:4000/author-api/articles
Content-Type: application/json

{
    "articleId":"",
    "title":"Article1 by Author 2",
    "category":"AI",
    "content":"test article on AI and its updated"
}


### delete/restore article by id
PATCH http//localhost:4000/author-api/articles
Content-Type: application/json

{
    "articleId":"",
    "isArticleActive":false
}