### register user
POST http://localhost:4000/auth/users
content-Type: application/json

{
    "firstName":"user5",
    "lastName":"",
    "email":"user5@mail.com",
    "role":"USER",
    "password":"user5",
    "profileImageURL":""
}

### user login
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "email":"user2@mail.com",
    "password":"user2"
}

### User Logout
GET http://localhost:4000/auth/logout


### read articles of all authors
GET http://localhost:4000/user-api/articles

### add comment
PUT http://localhost:4000/user-api/articles
Content-Type: application/json

{
    "articleId":"69be7ffeef974d4f182b6fae",
    "comment":"Nice one"
}

### change password
PUT http://localhost:4000/auth/password
Content-Type: application/json

{
    "currentPwd":"user1",
    "newPwd":"user1"
}